language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7

env:
  global:
    - CORE_BRANCH=master
  matrix:
    - DB=sqlite
    
branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

sudo: true
before_install:
  - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
  - bash ./before_install.sh password_policy $CORE_BRANCH $DB

script:
  # Test lint
  - cd ../server/apps/password_policy
  - find . -name \*.php -exec php -l "{}" \;

  # Run phpunit tests
  - cd tests
  - phpunit --configuration phpunit.xml

  # Create coverage report
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then php ocular.phar code-coverage:upload --format=php-clover clover.xml; fi"
  
matrix:
  include:
    - php: 5.4
      env: DB=mysql
    - php: 5.4
      env: DB=pgsql
  fast_finish: true
