name: CS-Check

on:
  pull_request:
  push:
    branches:
      - master
      - stable*

jobs:
  php-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['8']
  
    name: Lint php${{ matrix.php-versions }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Lint
        run: composer run lint

  php-cs-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['8']

    name: CS-Check php${{ matrix.php-versions }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up php
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: none

    - name: Install dependencies
      run: composer i

    - name: Run coding standards check
      run: composer run cs:check || ( echo 'Please run `composer run cs:fix` to format your code' && exit 1 )
